const TMDB_KEY = 'd1f3521379e4b0b81f8341967bda1b93';  
const IMAGE_BASE = 'https://image.tmdb.org/t/p/w500';  
let movies = [ { id: 0, title: 'The Odyssey', rating: '4.8 / 5', poster: 'https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg' }, { id: 1, title: 'Spider-Man', rating: '4.5 / 5', poster: 'https://image.tmdb.org/t/p/w500/iPOn6DinuVyLY17YM9mKuPofV08.jpg' }, { id: 2, title: 'The Invite', rating: '4.2 / 5', poster: 'https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg' }, { id: 3, title: 'Good Time', rating: '4.4 / 5', poster: 'https://image.tmdb.org/t/p/w500/yE1c9hj5Hf8a9KplAdRdhADqUro.jpg' }, { id: 4, title: 'Blue Film', rating: '4.1 / 5', poster: 'https://image.tmdb.org/t/p/w500/7yqMtaRMPgntGcDtYySv7XfTsDB.jpg' }, { id: 5, title: 'Rain Man', rating: '4.6 / 5', poster: 'https://image.tmdb.org/t/p/w500/iTNHwO896WKkaoPtpMMS74d8VNi.jpg' }, { id: 6, title: '13 Going on 30', rating: '4.3 / 5', poster: 'https://image.tmdb.org/t/p/w500/iNZdSIfhSCMtRILDNyhLn8UKeSG.jpg' }, { id: 7, title: 'Evil Dead', rating: '4.4 / 5', poster: 'https://image.tmdb.org/t/p/w500/ztadKzIIR0ERYqpHteaPFtk7inP.jpg' }, { id: 8, title: 'Leviticus', rating: '4.0 / 5', poster: 'https://image.tmdb.org/t/p/w500/gnAsZvBygplNpp8PtjoTEYv3VPB.jpg' }, { id: 9, title: 'The Furious', rating: '4.5 / 5', poster: 'https://image.tmdb.org/t/p/w500/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg' } ];  
let selectedIndex = 0;  
const gridEl = document.getElementById('grid');  
const spotlightPoster = document.getElementById('spotlight-poster');  
const spotlightRank = document.getElementById('spotlight-rank');  
const spotlightTitle = document.getElementById('spotlight-title');  
const spotlightRating = document.getElementById('spotlight-rating');  
const openEditorBtn = document.getElementById('open-editor-btn');  
const closeEditorBtn = document.getElementById('close-editor-btn');  
const editorModal = document.getElementById('editor-modal');  
const editorHeading = document.getElementById('editor-heading');  
const searchInput = document.getElementById('search-input');  
const searchBtn = document.getElementById('search-btn');  
const resultsContainer = document.getElementById('results-container');  
const ratingInput = document.getElementById('rating-input');  
const saveRatingBtn = document.getElementById('save-rating-btn'); 
function updateSpotlight() { const m = movies[selectedIndex]; spotlightRank.textContent = '#' + (selectedIndex + 1); spotlightPoster.style.backgroundImage = 'url(\" " + m.poster + " "\)'; spotlightTitle.textContent = m.title; const score = m.rating.replace(' / 5', ''); spotlightRating.innerHTML = score + ' <span class=\scale\>/ 5</span>'; }  
function renderReel() { gridEl.innerHTML = ''; for (let idx = 0; idx < movies.length; idx++) { const m = movies[idx]; const item = document.createElement('div'); item.className = 'reel-item ' + (idx === selectedIndex ? 'active' : ''); item.style.backgroundImage = 'url(\ + m.poster + \)'; item.onclick = function() { selectSlot(idx); }; const numTag = document.createElement('div'); numTag.className = 'reel-number'; numTag.textContent = '#' + (idx + 1); item.appendChild(numTag); gridEl.appendChild(item); } }  
function selectSlot(idx) { selectedIndex = idx; updateSpotlight(); renderReel(); } function openModal() { const m = movies[selectedIndex]; editorHeading.textContent = 'EDIT SLOT #' + (selectedIndex + 1) + ': ' + m.title.toUpperCase(); const score = m.rating.replace(' / 5', ''); ratingInput.value = isNaN(score) ? '4.5' : score; editorModal.classList.add('open'); } function closeModal() { editorModal.classList.remove('open'); } 
async function searchMovie() { const query = searchInput.value.trim(); if (!query) return; resultsContainer.innerHTML = 'Searching...'; try { const url = 'https://api.themoviedb.org/3/search/movie?api_key=' + TMDB_KEY + '&query=' + encodeURIComponent(query); const res = await fetch(url); const data = await res.json(); if (!data.results || data.results.length === 0) { resultsContainer.innerHTML = 'No movies found.'; return; } resultsContainer.innerHTML = ''; const list = data.results.slice(0, 10); for (let i = 0; i < list.length; i++) { const movie = list[i]; const card = document.createElement('div'); card.className = 'search-result-card'; if (movie.poster_path) { card.style.backgroundImage = 'url(\" " + IMAGE_BASE + movie.poster_path + " "\)'; } else { card.textContent = movie.title; } card.title = movie.title; card.onclick = function() { fetchPosters(movie); }; resultsContainer.appendChild(card); } } catch (err) { resultsContainer.innerHTML = 'Search failed'; } }  
async function fetchPosters(movie) { editorHeading.textContent = 'SELECT POSTER: ' + movie.title.toUpperCase(); movies[selectedIndex].title = movie.title; if (movie.poster_path) { movies[selectedIndex].poster = IMAGE_BASE + movie.poster_path; } updateSpotlight(); renderReel(); resultsContainer.innerHTML = 'Fetching posters...'; try { const url = 'https://api.themoviedb.org/3/movie/' + movie.id + '/images?api_key=' + TMDB_KEY; const res = await fetch(url); const data = await res.json(); if (!data.posters || data.posters.length === 0) { resultsContainer.innerHTML = 'Default poster applied.'; return; } resultsContainer.innerHTML = ''; for (let i = 0; i < data.posters.length; i++) { const p = data.posters[i]; const thumb = document.createElement('div'); thumb.className = 'poster-thumb'; const fullUrl = IMAGE_BASE + p.file_path; thumb.style.backgroundImage = 'url(\ + fullUrl + \)'; thumb.onclick = function() { movies[selectedIndex].poster = fullUrl; updateSpotlight(); renderReel(); }; resultsContainer.appendChild(thumb); } } catch (err) { console.error(err); } }  
openEditorBtn.onclick = openModal; closeEditorBtn.onclick = closeModal; editorModal.onclick = function(e) { if (e.target === editorModal) closeModal(); }; searchBtn.onclick = searchMovie; searchInput.onkeypress = function(e) { if (e.key === 'Enter') searchMovie(); }; saveRatingBtn.onclick = function() { const val = parseFloat(ratingInput.value); if (!isNaN(val)) { movies[selectedIndex].rating = val + ' / 5'; updateSpotlight(); renderReel(); closeModal(); } }; selectSlot(0); 
