const TMDB_KEY = 'd1f3521379e4b0b81f8341967bda1b93';  
const IMAGE_BASE = 'https://image.tmdb.org/t/p/w342';  
let movies = [ {id:0,title:'Slot 1',rating:'4.5 / 5',poster:''},{id:1,title:'Slot 2',rating:'4.5 / 5',poster:''},{id:2,title:'Slot 3',rating:'4.5 / 5',poster:''},{id:3,title:'Slot 4',rating:'4.5 / 5',poster:''},{id:4,title:'Slot 5',rating:'4.5 / 5',poster:''},{id:5,title:'Slot 6',rating:'4.5 / 5',poster:''},{id:6,title:'Slot 7',rating:'4.5 / 5',poster:''},{id:7,title:'Slot 8',rating:'4.5 / 5',poster:''},{id:8,title:'Slot 9',rating:'4.5 / 5',poster:''},{id:9,title:'Slot 10',rating:'4.5 / 5',poster:''} ];  
let selectedIndex = 0;  
const gridEl = document.getElementById('grid');  
const searchInput = document.getElementById('search-input');  
const searchBtn = document.getElementById('search-btn');  
const resultsContainer = document.getElementById('results-container');  
const ratingInput = document.getElementById('rating-input');  
const saveRatingBtn = document.getElementById('save-rating-btn');  
const editorHeading = document.getElementById('editor-heading'); 
function renderGrid() { gridEl.innerHTML = ''; for (let idx = 0; idx < movies.length; idx++) { const m = movies[idx]; const item = document.createElement('div'); item.className = 'movie-item ' + (idx === selectedIndex ? 'selected' : ''); item.onclick = function() { selectSlot(idx); }; const posterCard = document.createElement('div'); posterCard.className = 'poster-card'; if (m.poster) { posterCard.style.backgroundImage = 'url(' + JSON.stringify(m.poster) + ')'; } else { posterCard.textContent = idx + 1; } const details = document.createElement('div'); details.className = 'movie-details'; const titleEl = document.createElement('div'); titleEl.className = 'movie-title'; titleEl.textContent = m.title; const ratingEl = document.createElement('div'); ratingEl.className = 'rating-number'; ratingEl.textContent = m.rating; details.appendChild(titleEl); details.appendChild(ratingEl); item.appendChild(posterCard); item.appendChild(details); gridEl.appendChild(item); } } 
function selectSlot(idx) { selectedIndex = idx; editorHeading.innerText = 'Editing Slot ' + (idx + 1) + ': ' + movies[idx].title; const rNum = movies[idx].rating.replace(' / 5', ''); ratingInput.value = isNaN(rNum) ? '4.5' : rNum; renderGrid(); } 
async function searchMovie() { const query = searchInput.value.trim(); if (!query) return; resultsContainer.innerHTML = 'Searching TMDB...'; try { const url = 'https://api.themoviedb.org/3/search/movie?api_key=' + TMDB_KEY + '&query=' + encodeURIComponent(query); const res = await fetch(url); const data = await res.json(); if (!data.results || data.results.length === 0) { resultsContainer.innerHTML = 'No movies found.'; return; } resultsContainer.innerHTML = ''; const list = data.results.slice(0, 10); for (let i = 0; i < list.length; i++) { const movie = list[i]; const card = document.createElement('div'); card.className = 'search-result-card'; if (movie.poster_path) { card.style.backgroundImage = 'url(' + JSON.stringify(IMAGE_BASE + movie.poster_path) + ')'; } card.title = movie.title; card.onclick = function() { fetchPosters(movie); }; resultsContainer.appendChild(card); } } catch (err) { resultsContainer.innerHTML = 'Search failed'; } } 
async function fetchPosters(movie) { editorHeading.innerText = 'Select poster for: ' + movie.title; movies[selectedIndex].title = movie.title; if (movie.poster_path) { movies[selectedIndex].poster = IMAGE_BASE + movie.poster_path; } renderGrid(); resultsContainer.innerHTML = 'Fetching all movie posters...'; try { const url = 'https://api.themoviedb.org/3/movie/' + movie.id + '/images?api_key=' + TMDB_KEY; const res = await fetch(url); const data = await res.json(); if (!data.posters || data.posters.length === 0) { resultsContainer.innerHTML = 'Default poster selected.'; return; } resultsContainer.innerHTML = ''; for (let i = 0; i < data.posters.length; i++) { const p = data.posters[i]; const thumb = document.createElement('div'); thumb.className = 'poster-thumb'; const fullUrl = IMAGE_BASE + p.file_path; thumb.style.backgroundImage = 'url(' + JSON.stringify(fullUrl) + ')'; thumb.onclick = function() { movies[selectedIndex].poster = fullUrl; renderGrid(); }; resultsContainer.appendChild(thumb); } } catch (err) { console.error(err); } } 
searchBtn.onclick = searchMovie; searchInput.onkeypress = function(e) { if (e.key === 'Enter') searchMovie(); }; saveRatingBtn.onclick = function() { const val = parseFloat(ratingInput.value); if (!isNaN(val)) { movies[selectedIndex].rating = val + ' / 5'; renderGrid(); } }; async function loadDefaultMovies() { try { const url = 'https://api.themoviedb.org/3/movie/popular?api_key=' + TMDB_KEY; const res = await fetch(url); const data = await res.json(); if (data.results && data.results.length >= 10) { for (let idx = 0; idx < 10; idx++) { const m = data.results[idx]; movies[idx] = { id: idx, title: m.title.length > 14 ? m.title.substring(0, 12) + '...' : m.title, rating: (m.vote_average / 2).toFixed(1) + ' / 5', poster: m.poster_path ? (IMAGE_BASE + m.poster_path) : '' }; } renderGrid(); selectSlot(0); } } catch (e) { renderGrid(); } } loadDefaultMovies();
