const TMDB_KEY = 'd1f3521379e4b0b81f8341967bda1b93';  
const IMAGE_BASE = 'https://image.tmdb.org/t/p/w342';  
let movies = [ { id: 0, title: 'Inception', rating: '4.5 / 5', poster: 'https://image.tmdb.org/t/p/w342/oYuLEW9SpatialHQGlxy12fG2VJfl.jpg' }, { id: 1, title: 'Dark Knight', rating: '4.7 / 5', poster: 'https://image.tmdb.org/t/p/w342/qJ2tW6WMUDux911r6m7haRef0WH.jpg' }, { id: 2, title: 'Interstellar', rating: '4.6 / 5', poster: 'https://image.tmdb.org/t/p/w342/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg' }, { id: 3, title: 'Dune Part 2', rating: '4.5 / 5', poster: 'https://image.tmdb.org/t/p/w342/czembW0RhiL1uMOODjT5rJ8bkdn.jpg' }, { id: 4, title: 'Oppenheimer', rating: '4.4 / 5', poster: 'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGvFioRer1A.jpg' }, { id: 5, title: 'Gladiator II', rating: '4.2 / 5', poster: 'https://image.tmdb.org/t/p/w342/v92b45FKn04b7yeg8sZc29eOqjH.jpg' }, { id: 6, title: 'Pulp Fiction', rating: '4.5 / 5', poster: 'https://image.tmdb.org/t/p/w342/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg' }, { id: 7, title: 'Shawshank', rating: '4.8 / 5', poster: 'https://image.tmdb.org/t/p/w342/9cqN1wXHQyBhGedW6WiA3TYBrmL.jpg' }, { id: 8, title: 'The Batman', rating: '4.3 / 5', poster: 'https://image.tmdb.org/t/p/w342/74xTEgt7R36Fpooo50r9T25onhq.jpg' }, { id: 9, title: 'Fight Club', rating: '4.5 / 5', poster: 'https://image.tmdb.org/t/p/w342/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg' } ];  
let selectedIndex = 0;  
const gridEl = document.getElementById('grid');  
const searchInput = document.getElementById('search-input');  
const searchBtn = document.getElementById('search-btn');  
const resultsContainer = document.getElementById('results-container');  
const ratingInput = document.getElementById('rating-input');  
const saveRatingBtn = document.getElementById('save-rating-btn');  
const editorHeading = document.getElementById('editor-heading'); 
function renderGrid() { gridEl.innerHTML = ''; for (let idx = 0; idx < movies.length; idx++) { const m = movies[idx]; const item = document.createElement('div'); item.className = 'movie-item ' + (idx === selectedIndex ? 'selected' : ''); item.onclick = function() { selectSlot(idx); }; const posterCard = document.createElement('div'); posterCard.className = 'poster-card'; if (m.poster) { posterCard.style.backgroundImage = 'url(\" " + m.poster + " "\)'; } else { posterCard.textContent = idx + 1; } const details = document.createElement('div'); details.className = 'movie-details'; const titleEl = document.createElement('div'); titleEl.className = 'movie-title'; titleEl.textContent = m.title; const ratingEl = document.createElement('div'); ratingEl.className = 'rating-number'; ratingEl.textContent = m.rating; details.appendChild(titleEl); details.appendChild(ratingEl); item.appendChild(posterCard); item.appendChild(details); gridEl.appendChild(item); } } 
function selectSlot(idx) { selectedIndex = idx; editorHeading.innerText = 'Editing Slot ' + (idx + 1) + ': ' + movies[idx].title; const rNum = movies[idx].rating.replace(' / 5', ''); ratingInput.value = isNaN(rNum) ? '4.5' : rNum; renderGrid(); } 
async function searchMovie() { const query = searchInput.value.trim(); if (!query) return; resultsContainer.innerHTML = 'Searching...'; try { const url = 'https://api.themoviedb.org/3/search/movie?api_key=' + TMDB_KEY + '&query=' + encodeURIComponent(query); const res = await fetch(url); const data = await res.json(); if (!data.results || data.results.length === 0) { resultsContainer.innerHTML = 'No movies found.'; return; } resultsContainer.innerHTML = ''; const list = data.results.slice(0, 10); for (let i = 0; i < list.length; i++) { const movie = list[i]; const card = document.createElement('div'); card.className = 'search-result-card'; if (movie.poster_path) { card.style.backgroundImage = 'url(\" " + IMAGE_BASE + movie.poster_path + " "\)'; } else { card.textContent = movie.title; } card.title = movie.title; card.onclick = function() { fetchPosters(movie); }; resultsContainer.appendChild(card); } } catch (err) { resultsContainer.innerHTML = 'Search failed'; } } 
async function fetchPosters(movie) { editorHeading.innerText = 'Select poster for: ' + movie.title; movies[selectedIndex].title = movie.title; if (movie.poster_path) { movies[selectedIndex].poster = IMAGE_BASE + movie.poster_path; } renderGrid(); resultsContainer.innerHTML = 'Fetching posters...'; try { const url = 'https://api.themoviedb.org/3/movie/' + movie.id + '/images?api_key=' + TMDB_KEY; const res = await fetch(url); const data = await res.json(); if (!data.posters || data.posters.length === 0) { resultsContainer.innerHTML = 'Default poster applied.'; return; } resultsContainer.innerHTML = ''; for (let i = 0; i < data.posters.length; i++) { const p = data.posters[i]; const thumb = document.createElement('div'); thumb.className = 'poster-thumb'; const fullUrl = IMAGE_BASE + p.file_path; thumb.style.backgroundImage = 'url(\" " + fullUrl + " "\)'; thumb.onclick = function() { movies[selectedIndex].poster = fullUrl; renderGrid(); }; resultsContainer.appendChild(thumb); } } catch (err) { console.error(err); } } 
searchBtn.onclick = searchMovie; searchInput.onkeypress = function(e) { if (e.key === 'Enter') searchMovie(); }; saveRatingBtn.onclick = function() { const val = parseFloat(ratingInput.value); if (!isNaN(val)) { movies[selectedIndex].rating = val + ' / 5'; renderGrid(); } }; renderGrid(); selectSlot(0); 
